rootProject.name = "kotlin-skeleton"

include(":apps:api")
include(":modules:platform")
include(":modules:auth")
include(":modules:auth-social")
include(":modules:auth-social-google")
include(":modules:auth-social-kakao")
include(":modules:auth-social-naver")
include(":modules:notification")
include(":modules:notification-sse")
include(":modules:notification-slack")
include(":modules:config-aws-ssm")
include(":modules:idempotency")
include(":modules:persistence-jpa")
include(":modules:persistence-jdbc")
include(":modules:redis-core")
include(":modules:redis-lock")
