-- Flyway 없이 spring.sql.init 로 스키마를 만드는 예시 (v0 용). 실제 앱은 src/main/resources/schema.sql
create table if not exists schema_sql_probe (
    id   bigint generated by default as identity primary key,
    name varchar(50) not null
);

-- 모듈 마이그레이션을 그대로 복사한 예 (docs/schema-management.md Mode B). PG 는 create index if not exists 라 재실행이 멱등이다.
-- modules:job-queue-jdbc — PostgreSQL 테이블 기반 재시도 큐 (Redis 없음, FOR UPDATE SKIP LOCKED)
create table if not exists skeleton_jobs (
    id            bigint generated by default as identity primary key,
    job_type      varchar(128) not null,
    payload_json  text         not null,
    status        varchar(16)  not null,            -- PENDING | RUNNING | DONE | DEAD
    attempts      int          not null default 0,
    max_attempts  int          not null,
    next_run_at   timestamptz  not null,
    locked_by     varchar(128) null,
    locked_at     timestamptz  null,
    last_error    text         null,
    created_at    timestamptz  not null,
    updated_at    timestamptz  not null
);
create index if not exists idx_skeleton_jobs_claim on skeleton_jobs (status, next_run_at);
create index if not exists idx_skeleton_jobs_running on skeleton_jobs (status, locked_at);
