-- modules:legal-jdbc — 약관 · 동의 (PostgreSQL).
-- legal_consents: 동의 사건 기록. **더하기만 한다** — 트리거가 막는 것: 지우기(익명화된 줄만 예외), 고치기(익명화 · IP/UA 비우기만 예외).
-- 한 (주체 · 종류 · 참조) 안의 순번 seq 가 유니크 키의 일부라서, 같은 순번을 동시에 넣으려는 쪽이 진다 (멱등 기록의 근거).
create table if not exists legal_consents (
    id            bigint        generated by default as identity primary key,
    subject_type  varchar(32)   not null,                 -- 'account' 가 기본
    subject_id    varchar(128)  not null,                 -- 계정이면 계정 id, 지워진 뒤에는 'deleted:<해시>'
    document_type varchar(32)   not null,
    version       varchar(32)   not null,
    content_sha256 varchar(64)  not null,                 -- 그때 본 언어 원문(정규화본)의 해시
    locale        varchar(35)   not null,
    action        varchar(16)   not null,                 -- AGREED · WITHDRAWN
    source        varchar(32)   not null,                 -- sign-up · consent · re-consent · checkout · withdraw …
    reference_id  varchar(128)  not null default '',      -- 주문 같은 참조. 없으면 빈 문자열
    seq           integer       not null,
    ip            varchar(64),
    user_agent    varchar(255),
    created_at    timestamptz   not null,
    constraint uq_legal_consents_event unique (subject_type, subject_id, document_type, reference_id, seq)
);
create index if not exists idx_legal_consents_subject on legal_consents (subject_type, subject_id, id);
create index if not exists idx_legal_consents_created on legal_consents (created_at);

create or replace function legal_consents_guard() returns trigger as $$
begin
    if tg_op = 'DELETE' then
        if old.subject_id like 'deleted:%' then
            return old;
        end if;
        raise exception 'legal_consents is append-only: a row is deleted only after it was anonymized';
    end if;
    if new.id is distinct from old.id or new.subject_type is distinct from old.subject_type or new.document_type is distinct from old.document_type
       or new.version is distinct from old.version or new.content_sha256 is distinct from old.content_sha256 or new.locale is distinct from old.locale
       or new.action is distinct from old.action or new.source is distinct from old.source or new.reference_id is distinct from old.reference_id
       or new.seq is distinct from old.seq or new.created_at is distinct from old.created_at then
        raise exception 'legal_consents is append-only: only the personal columns may change (anonymize, scrub)';
    end if;
    if new.subject_id is distinct from old.subject_id and new.subject_id not like 'deleted:%' then
        raise exception 'legal_consents: a subject id may only be replaced by a tombstone';
    end if;
    if (new.ip is not null and new.ip is distinct from old.ip) or (new.user_agent is not null and new.user_agent is distinct from old.user_agent) then
        raise exception 'legal_consents: ip and user agent may only be cleared';
    end if;
    return new;
end;
$$ language plpgsql;

drop trigger if exists legal_consents_guard_trg on legal_consents;
create trigger legal_consents_guard_trg before update or delete on legal_consents for each row execute function legal_consents_guard();

-- legal_document_versions: 판 장부 — 처음 본 순간의 상태. 어떤 경우에도 고치거나 지우지 않는다.
create table if not exists legal_document_versions (
    id             bigint       generated by default as identity primary key,
    document_type  varchar(32)  not null,
    version        varchar(32)  not null,
    locale         varchar(35)  not null,
    status         varchar(16)  not null,                 -- DRAFT · REVIEWED
    content_sha256 varchar(64)  not null,
    effective_from timestamptz,
    recorded_at    timestamptz  not null,
    constraint uq_legal_document_versions unique (document_type, version, locale)
);

create or replace function legal_document_versions_guard() returns trigger as $$
begin
    raise exception 'legal_document_versions is append-only';
end;
$$ language plpgsql;

drop trigger if exists legal_document_versions_guard_trg on legal_document_versions;
create trigger legal_document_versions_guard_trg before update or delete on legal_document_versions for each row execute function legal_document_versions_guard();
