-- 이 모듈의 코드 생성 · 테스트용 예시 스키마 (PostgreSQL). 앱은 자기 db/migration/postgresql 폴더를 가리킨다.
create table if not exists jooq_probe (
    id          bigint generated by default as identity primary key,
    name        varchar(100) not null,
    happened_at timestamptz  not null,
    local_wall  timestamp,
    created_at  timestamptz  not null,
    updated_at  timestamptz  not null
);
