#!/usr/bin/env python3
"""
tzdata zone.tab (또는 zone1970.tab) → country-zones.tsv 생성.

  python3 modules/time/scripts/gen-country-zones.py /usr/share/zoneinfo/zone.tab \
      modules/time/src/main/resources/dev/sumin/skeleton/time/country-zones.tsv \
      [../react-skeleton/src/lib/time/country-zones.ts]

출력 한 줄: <ISO 3166-1 alpha-2>\t<대표 zone>\t<zone,zone,...(대표 포함, 전체)>
대표 zone: 시간대가 하나면 그것, 여러 개면 아래 DEFAULTS(수도/최대 도시), 없으면 zone.tab 첫 줄.
"""
import sys, collections

# 시간대가 여러 개인 나라의 대표값. zone.tab 첫 줄이 대표가 아닌 경우가 많아서 (BR=Noronha, AU=Lord_Howe) 명시한다.
DEFAULTS = {
    "US": "America/New_York", "CA": "America/Toronto", "MX": "America/Mexico_City",
    "BR": "America/Sao_Paulo", "AR": "America/Argentina/Buenos_Aires", "CL": "America/Santiago",
    "EC": "America/Guayaquil", "GL": "America/Nuuk",
    "RU": "Europe/Moscow", "UA": "Europe/Kyiv", "KZ": "Asia/Almaty", "MN": "Asia/Ulaanbaatar",
    "CN": "Asia/Shanghai", "ID": "Asia/Jakarta", "MY": "Asia/Kuala_Lumpur", "PS": "Asia/Gaza", "CY": "Asia/Nicosia",
    "AU": "Australia/Sydney", "NZ": "Pacific/Auckland", "PG": "Pacific/Port_Moresby", "FM": "Pacific/Pohnpei",
    "KI": "Pacific/Tarawa", "PF": "Pacific/Tahiti",
    "ES": "Europe/Madrid", "PT": "Europe/Lisbon", "FR": "Europe/Paris", "DE": "Europe/Berlin", "GB": "Europe/London",
    "CD": "Africa/Kinshasa", "AQ": "Antarctica/McMurdo",
}

src, out_tsv = sys.argv[1], sys.argv[2]
out_ts = sys.argv[3] if len(sys.argv) > 3 else None

zones = collections.OrderedDict()
for line in open(src, encoding="utf-8"):
    if not line.strip() or line.startswith("#"):
        continue
    cc, _coords, zone, *_ = line.rstrip("\n").split("\t")
    for c in cc.split(","):          # zone1970.tab 은 "KR,JP" 처럼 여러 국가가 한 줄
        zones.setdefault(c, [])
        if zone not in zones[c]:
            zones[c].append(zone)

rows = []
for cc in sorted(zones):
    zs = zones[cc]
    default = zs[0] if len(zs) == 1 else DEFAULTS.get(cc, zs[0])
    if default not in zs:
        raise SystemExit(f"{cc}: default {default} not in {zs}")
    ordered = [default] + [z for z in zs if z != default]
    rows.append((cc, default, ordered))

with open(out_tsv, "w", encoding="utf-8") as f:
    f.write(f"# generated from {src.split('/')[-1]} by gen-country-zones.py — 손으로 고치지 말 것\n")
    for cc, default, ordered in rows:
        f.write(f"{cc}\t{default}\t{','.join(ordered)}\n")

if out_ts:
    with open(out_ts, "w", encoding="utf-8") as f:
        f.write("// generated by kotlin-skeleton/modules/time/scripts/gen-country-zones.py — 손으로 고치지 말 것\n")
        f.write("// key: ISO 3166-1 alpha-2, value: IANA zone 목록 (첫 번째가 대표)\n")
        f.write("export const COUNTRY_ZONES: Readonly<Record<string, readonly string[]>> = {\n")
        for cc, _d, ordered in rows:
            f.write(f"  {cc}: [{', '.join(repr(z).replace(chr(39), chr(39)) for z in ordered)}],\n".replace("'", "'"))
        f.write("}\n")
print(f"{len(rows)} countries → {out_tsv}" + (f", {out_ts}" if out_ts else ""))
