-- 테스트 전용: 시각 3종 왕복(JVM 시간대 무관) 검증용 테이블
create table utc_probe (
    id            bigint generated by default as identity primary key,
    happened_at   timestamptz not null,   -- Instant (UTC)
    birthday      date        null,       -- LocalDate (변환 없음)
    local_wall    timestamp   null        -- LocalDateTime (벽시계)
);
