-- modules:alert-jdbc — 주인 경보 기록 (PostgreSQL). (종류 · 키)마다 **한 행**.
-- 같은 (종류 · 키)가 최소 간격 안에 다시 오면 새 행이 아니라 suppressed_count 만 올린다 (한 문장짜리 조건부 갱신 — 여러 스레드 · 서버가 동시에 와도 보내기는 하나).
-- 간격이 지나 다시 오면 그때까지 접어 둔 수(last_suppressed)를 실어 한 번 더 보낸다. 비밀 값은 싣지 않는다 — title · detail 은 마스킹을 거친 한 줄.
create table if not exists alerts (
    id                bigint        generated by default as identity primary key,
    kind              varchar(64)   not null,                 -- AlertKind.name
    alert_key         varchar(80)   not null default '',      -- 종류 안에서 따로 세는 키 (주문번호 · 작업 종류 …). 없으면 빈 문자열
    severity          varchar(10)   not null,                 -- INFO · WARN · ERROR · CRITICAL
    title             varchar(200)  not null,
    detail            varchar(1000) not null default '',
    first_at          timestamptz   not null,                 -- 이 (종류 · 키)가 처음 온 때
    occurred_at       timestamptz   not null,                 -- 가장 최근에 온 때
    sent_at           timestamptz   not null,                 -- 가장 최근에 내보내기로 한 때 — 간격의 기준
    occurrences       bigint        not null default 1,       -- 지금까지 온 수 (보낸 것 + 접은 것)
    suppressed_count  integer       not null default 0,       -- 마지막으로 보낸 뒤 접은 수
    last_suppressed   integer       not null default 0,       -- 마지막으로 보낸 알림에 「N건 더」로 실린 수
    constraint uq_alerts_kind_key unique (kind, alert_key)
);
create index if not exists idx_alerts_occurred on alerts (occurred_at);
