-- modules:job-queue-jdbc — PostgreSQL 테이블 기반 재시도 큐 (Redis 없음, FOR UPDATE SKIP LOCKED)
create table if not exists jobs (
    id            bigint generated by default as identity primary key,
    job_type      varchar(128) not null,
    payload_json  text         not null,
    status        varchar(16)  not null,            -- PENDING | RUNNING | DONE | DEAD
    attempts      int          not null default 0,
    max_attempts  int          not null,
    next_run_at   timestamptz  not null,
    locked_by     varchar(128) null,
    locked_at     timestamptz  null,
    last_error    text         null,
    created_at    timestamptz  not null,
    updated_at    timestamptz  not null
);
create index if not exists idx_jobs_claim on jobs (status, next_run_at);
create index if not exists idx_jobs_running on jobs (status, locked_at);
