plugins {
    id("org.springframework.boot")
}

dependencies {
    implementation(project(":modules:platform"))
    implementation(project(":modules:auth"))
    implementation(project(":modules:auth-social"))
    implementation(project(":modules:auth-social-google"))
    implementation(project(":modules:auth-social-kakao"))
    implementation(project(":modules:auth-social-naver"))
    implementation(project(":modules:async"))
    implementation(project(":modules:config-aws-ssm"))
    implementation(project(":modules:crypto"))
    implementation(project(":modules:event-kafka"))
    implementation(project(":modules:idempotency"))
    implementation(project(":modules:json"))
    implementation(project(":modules:notification"))
    implementation(project(":modules:notification-slack"))
    implementation(project(":modules:notification-sse"))
    implementation(project(":modules:notification-websocket"))
    implementation(project(":modules:payment"))
    implementation(project(":modules:payment-stripe"))
    implementation(project(":modules:payment-toss"))
    implementation(project(":modules:persistence-jdbc"))
    implementation(project(":modules:persistence-jpa"))
    implementation(project(":modules:redis-cache"))
    implementation(project(":modules:redis-core"))
    implementation(project(":modules:redis-lock"))
    implementation(project(":modules:redis-rate-limit"))
    implementation(project(":modules:scheduler"))
    implementation(project(":modules:storage"))
    implementation(project(":modules:storage-s3"))

    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3")
    implementation("org.springframework.boot:spring-boot-starter-data-jdbc")
    implementation("org.springframework.boot:spring-boot-starter-flyway")
    implementation("org.springframework.boot:spring-boot-starter-webmvc")
    implementation("org.flywaydb:flyway-mysql")
    implementation("org.springframework.security:spring-security-core")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("tools.jackson.module:jackson-module-kotlin")

    developmentOnly("org.springframework.boot:spring-boot-devtools")
    runtimeOnly("com.mysql:mysql-connector-j")

    testImplementation("org.springframework.boot:spring-boot-starter-actuator-test")
    testImplementation("org.springframework.boot:spring-boot-starter-data-jdbc-test")
    testImplementation("org.springframework.boot:spring-boot-starter-flyway-test")
    testImplementation("org.springframework.boot:spring-boot-starter-webmvc-test")
    testImplementation("org.springframework.boot:spring-boot-testcontainers")
    testImplementation(project(":modules:notification-slack"))
    testImplementation("org.springframework.security:spring-security-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    testImplementation("org.testcontainers:testcontainers-junit-jupiter")
    testImplementation("org.testcontainers:testcontainers-mysql")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}
